# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 21:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inspection_Date', models.DateField()),
                ('Inspection_Closed_Business', models.BooleanField()),
                ('Inspection_Result', models.CharField(max_length=50)),
                ('Inspection_Score', models.IntegerField()),
                ('Inspection_Serial_Num', models.CharField(max_length=50, unique=True)),
                ('Inspection_Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=50)),
                ('Business_ID', models.CharField(max_length=50, unique=True)),
                ('City', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('Name', models.CharField(max_length=50)),
                ('Program_Identifier', models.CharField(max_length=50, unique=True)),
                ('Zip_Code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Violation_Description', models.CharField(max_length=150)),
                ('Violation_Points', models.IntegerField()),
                ('Violation_Record_ID', models.CharField(max_length=50, unique=True)),
                ('Violation_Type', models.CharField(max_length=50)),
                ('Inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.Inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.Restaurant'),
        ),
    ]
