# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Inspection_Date',
            field=models.DateTimeField(),
        ),
    ]
