# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0002_auto_20161113_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Inspection_Score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
