# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0004_auto_20161113_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Address',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Description',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Program_Identifier',
            field=models.CharField(max_length=75),
        ),
    ]
