# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0005_auto_20161113_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Zip_Code',
            field=models.CharField(max_length=50),
        ),
    ]
