# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0006_auto_20161113_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Total_Inspection_Closed_Business',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Total_Inspection_Score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Total_Violation_Points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
