# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0007_auto_20161114_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Total_Inspection_Score',
        ),
    ]
